# Default values for mariabackup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  cronjob:
    timeZone: "UTC"
    schedule: "0 5 * * *"
  mariadb:
    hostname: "mariadb-secondary.mariadb.svc.cluster.local"
    port: "3306"
    username: "maria-user"
    password: "maria-pass"
  rclone:
    remotePath: "mariabackup-dumps"
    envVars:

      ##### google cloud storage
      RCLONE_CONFIG_RMT_TYPE: "google cloud storage"
      RCLONE_CONFIG_RMT_BUCKET_POLICY_ONLY: "true"
      RCLONE_CONFIG_RMT_LOCATION: "eu"
      RCLONE_CONFIG_RMT_PROJECT_NUMBER: "..."
      RCLONE_CONFIG_RMT_SERVICE_ACCOUNT_CREDENTIALS: |
        { 
          "type": "service_account",
          ...
        }

      ##### s3 storage
      # RCLONE_CONFIG_RMT_TYPE: "s3"
      # RCLONE_CONFIG_RMT_PROVIDER: "AWS"
      # RCLONE_CONFIG_RMT_ACCESS_KEY_ID: "..."
      # RCLONE_CONFIG_RMT_SECRET_ACCESS_KEY: "..."
      # RCLONE_CONFIG_RMT_ENDPOINT: "..."

      ##### other storage types (see https://rclone.org/docs/)

image:
  repository: "docker.io/caligari/mariabackup"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

